package dependencies

object Dependencies {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${BuildDependenciesVersions.KOTLIN}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${BuildDependenciesVersions.APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${BuildDependenciesVersions.MATERIAL}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${BuildDependenciesVersions.COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${BuildDependenciesVersions.COROUTINES}"
    const val ROOM = "androidx.room:room-runtime:${BuildDependenciesVersions.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${BuildDependenciesVersions.ROOM}"
    const val RECYCLE_VIEW = "androidx.recyclerview:recyclerview:${BuildDependenciesVersions.RECYCLE_VIEW}"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${BuildDependenciesVersions.NAVIGATION}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${BuildDependenciesVersions.NAVIGATION}"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${BuildDependenciesVersions.LIFECYCLE}"
    const val LIFECYCLE_LIVE_DATA = "androidx.lifecycle:lifecycle-livedata-ktx:${BuildDependenciesVersions.LIFECYCLE}"
    const val LIFECYCLE_PROCESS = "androidx.lifecycle:lifecycle-process:${BuildDependenciesVersions.LIFECYCLE}"
    const val CORE_KTX = "androidx.core:core-ktx:${BuildDependenciesVersions.CORE_KTX}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${BuildDependenciesVersions.FRAGMENT_KTX}"
    const val CONSTRAIN_LAYOUT = "androidx.constraintlayout:constraintlayout:${BuildDependenciesVersions.CONSTRAIN_LAYOUT}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${BuildDependenciesVersions.SWIPE_REFRESH_LAYOUT}"
    const val PAGING = "androidx.paging:paging-runtime-ktx:${BuildDependenciesVersions.PAGING}"
    const val DAGGER = "com.google.dagger:dagger:${BuildDependenciesVersions.DAGGER}"
    const val TIMBER = "com.jakewharton.timber:timber:${BuildDependenciesVersions.TIMBER}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${BuildDependenciesVersions.RETROFIT}"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-moshi:${BuildDependenciesVersions.RETROFIT}"
    const val MOSHI = "com.squareup.moshi:moshi:${BuildDependenciesVersions.MOSHI}"
    const val MOSHI_ADAPTERS = "com.squareup.moshi:moshi-adapters:${BuildDependenciesVersions.MOSHI}"
    const val LOGGING = "com.squareup.okhttp3:logging-interceptor:${BuildDependenciesVersions.OKHTTP}"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:${BuildDependenciesVersions.OKHTTP}"
    const val COIL = "io.coil-kt:coil:${BuildDependenciesVersions.COIL}"
    const val ANDROID_SDP = "com.intuit.sdp:sdp-android:${BuildDependenciesVersions.ANDROID_SDP}"
    const val PIN_EDIT_TEXT = "com.github.poovamraj:PinEditTextField:${BuildDependenciesVersions.PIN_EDIT_TEXT}"
    const val MULTIDEX = "androidx.multidex:multidex:${BuildDependenciesVersions.MULTIDEX}"
    const val PERMISSION_DISPATCHER = "com.github.permissions-dispatcher:ktx:${BuildDependenciesVersions.PERMISSION_DISPATCHER}"
    const val LOTTIE = "com.airbnb.android:lottie:${BuildDependenciesVersions.LOTTIE}"
    const val GSON = "com.google.code.gson:gson:${BuildDependenciesVersions.GSON}"
    const val LOKALISE = "com.lokalise.android:sdk:${BuildDependenciesVersions.LOKALISE}"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom:${BuildDependenciesVersions.FIREBASE_BOM}"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase:firebase-crashlytics-ktx"
    const val FIREBASE_ANALYTICS = "com.google.firebase:firebase-analytics-ktx"
    const val FIREBASE_PERFORMANCE_MONITOR = "com.google.firebase:firebase-perf-ktx"
    const val FIREBASE_MESSAGING = "com.google.firebase:firebase-messaging"
    const val PDF_VIEWER = "com.github.barteksc:android-pdf-viewer:${BuildDependenciesVersions.PDF_VIEWER}"
    const val SUBSAMPLING_SCALE_IMAGE = "com.davemorrissey.labs:subsampling-scale-image-view:${BuildDependenciesVersions.SUBSAMPLING_SCALE_IMAGE}"
    const val CLEVER_TAP = "com.clevertap.android:clevertap-android-sdk:${BuildDependenciesVersions.CLEVER_TAP}"
    const val INSTALL_REFEERER = "com.android.installreferrer:installreferrer:${BuildDependenciesVersions.INSTALL_REFEERAR}"
    const val DESUGAR_JDK = "com.android.tools:desugar_jdk_libs:${BuildDependenciesVersions.DESUGAR_JDK}"
    const val GOOGLE_TAG_MANAGER = "com.google.android.gms:play-services-tagmanager:${BuildDependenciesVersions.GOOGLE_TAG_MANAGER_VERSION}"
    const val FACEBOOK_SDK = "com.facebook.android:facebook-android-sdk:latest.release"
    const val BRANCH_SDK = "io.branch.sdk.android:library:${BuildDependenciesVersions.BRANCH_SDK_VERSION}"
    const val GOOGLE_ADS_IDENTIFIER = "com.google.android.gms:play-services-ads-identifier:${BuildDependenciesVersions.GOOGLE_ADS_VERSION}" // this for branch required
    //  optional Chrome Tab matching (enables 100% guaranteed matching based on cookies)
    const val BRANCH_CHROME_SUPPORT = "androidx.browser:browser:${BuildDependenciesVersions.BRANCH_BROWSER_CHROME_SUPPORT}"
    const val FRESH_CHAT = "com.github.freshworks:freshchat-android:${BuildDependenciesVersions.FRESH_CHAT}"
}
